title: Alex Podikoglou
email: alex.podikoglou@gmail.com
description: >-
  I’m a Computer Science student from Thessaloniki. I like to dabble in
  different technologies and read about computers and linguistics.
baseurl: ""
url: "https://podikoglou.eu"

github_username: podikoglou

collections:
  misc:
    output: true
    permalink: /:name

plugins:
  - jekyll-feed
  - jekyll-seo-tag

markdown: kramdown

kramdown:
  input: GFM
  hard_wrap: false

highlighter: rouge
